version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: '.'
    volumes:
      - ./:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: '.'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "kgb_db"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData: