version: "3.9"
services:
  php-apache:
    ports:
      - "8080:80"
    build: '.'
    volumes:
      - ./:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: '.'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "kgb_db"
    volumes:
      - dbData:/var/lib/mysql
  phpmya:
    ports: 
      - 8899:80
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "super-secret-password"
      UPLOAD_LIMIT: 20M
    
volumes:
  app:
  dbData: