# fly.toml file generated for international-spy-agency on 2023-01-15T20:15:00+01:00

app = "international-spy-agency"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
